version: "3"
networks:
  web:
    external: true
services:  
  mongo:
    container_name: mongo 
    image: mongo
    volumes:
      - ${PWD}/datadir:/data/db 
    networks:
      - web
    labels:
      - traefik.enable=false
    expose:
      - "27017"
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - "TOKEN=${TELEGRAM_BOT_TOKEN}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
    volumes:
      - ${PWD}:/app    
    depends_on:
      - mongo
    networks:
      - web
    expose:
      - "3000"
    