version: "3"

services:   
  mongo:
    container_name: mongo 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/datadir:/data/db
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - "TOKEN=${TELEGRAM_BOT_TOKEN}"
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app
    depends_on:
      - mongo